version: 2.1

jobs:
  build-and-test:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - checkout
      - run:
          name: Run nvidia-smi
          command: |
            nvidia-smi

  nix-build:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - restore_cache:
          key: nix-store
      - checkout
      - run:
          name: Install Nix
          command: |
            sh <(curl -L https://nixos.org/nix/install) --daemon < /dev/null
            echo "source $HOME/.nix-profile/etc/profile.d/nix.sh" >> $BASH_ENV
            # For cudatoolkit (TODO: allowUnfreePredicate for cuda only)
            mkdir -p $HOME/.config/nixpkgs
            echo '{ allowUnfree = true; }' > $HOME/.config/nixpkgs/config.nix
            # Enable CUDA support in sandboxed builds
            echo 'extra-sandbox-paths = /run/opengl-driver/lib=/usr/lib/x86_64-linux-gnu /dev/nvidiactl /dev/nvidia-uvm /dev/nvidia0' >> /etc/nix/nix.conf
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
            #cachix use something-i-still-need-to-set-up
      - run:
          name: CUDA smoke test
          command: |
            nvidia-smi
      - run:
          name: Build, install, and test isce3
          command: |
            nix-build
      - save_cache:
          key: nix-store
          when: always
          paths:
            - /nix

workflows:
  pr-checks:
    jobs:
      - nix-build
