version: 2.1

jobs:
  build-and-test:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - checkout
      - run:
          name: Run nvidia-smi
          command: |
            nvidia-smi

  nix-build:
    docker:
      - image: nvidia/cuda:11.4.2-devel-centos7
    steps:
      - restore_cache:
          key: nix-store
      - run:
          name: Install Nix as root
          # Based on https://github.com/NixOS/docker
          # (The ordinary Nix install script doesn't work as root)
          command: |
            yum install -y ca-certificates wget
            export NIX_VERSION=2.3.15
            wget https://nixos.org/releases/nix/nix-${NIX_VERSION}/nix-${NIX_VERSION}-$(uname -m)-linux.tar.xz
            tar xf nix-${NIX_VERSION}-$(uname -m)-linux.tar.xz
            groupadd -g 30000 -r nixbld
            for i in $(seq 1 30); do useradd -r -d /var/empty -c "Nix build user $i" -u $((30000 + i)) -G nixbld nixbld$i ; done
            mkdir -m 0755 /etc/nix
            echo 'sandbox = false' > /etc/nix/nix.conf
            mkdir -m 0755 /nix && USER=root sh nix-${NIX_VERSION}-$(uname -m)-linux/install
            echo 'source /nix/var/nix/profiles/default/etc/profile.d/nix.sh' >> $BASH_ENV
            echo 'export PATH=/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:$PATH' >> $BASH_ENV
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
            #cachix use something-i-still-need-to-set-up
      - checkout
      - run:
          name: CUDA smoke test
          command: |
            nvidia-smi
      - save_cache:
          key: nix-store
          when: always
          paths:
            - /nix

workflows:
  pr-checks:
    jobs:
      - nix-build
