version: 2.1

jobs:
  build-and-test:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - checkout
      - run:
          name: Run nvidia-smi
          command: |
            nvidia-smi

  nix-build:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - restore_cache:
          key: nix-store
      - checkout
      - run:
          name: Install Nix
          command: |
            curl -L https://nixos.org/nix/install | sh
            echo "source $HOME/.nix-profile/etc/profile.d/nix.sh" >> $BASH_ENV
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
            #cachix use something-i-still-need-to-set-up
      - run:
          name: CUDA smoke test
          command: |
            nvidia-smi
      - save_cache:
          key: nix-store
          when: always
          paths:
            - /nix

workflows:
  pr-checks:
    jobs:
      - nix-build
