version: 2.1

executors:
  linux-gpu-small-cuda11:
    resource_class: gpu.nvidia.small
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
      docker_layer_caching: true
    environment:
      CUDA_ARCH: "61"

  linux-gpu-medium-cuda11:
    resource_class: gpu.nvidia.medium
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
      docker_layer_caching: true
    environment:
      CUDA_ARCH: "75"

jobs:
  linux-gpu-build-and-test:
    parameters:
      executor:
        type: executor
        description: Linux GPU runner
        default: linux-gpu-medium-cuda11
      imageset:
        type: enum
        enum: [centos7-gpu, ubuntu2004-gpu]
        description: Docker image family
        default: centos7-gpu
      cmake:
        type: string
        description: CMake version string
        default: ""
      cuda:
        type: string
        description: CUDA version string
        default: 11-4
      gcc:
        type: string
        description: GCC version string
        default: ""
      gdal:
        type: string
        description: GDAL version string
        default: ""
      eigen:
        type: string
        description: Eigen version string
        default: ""
      pybind11:
        type: string
        description: pybind11 version string
        default: ""
      python:
        type: string
        description: Python version string
        default: ""
      build_type:
        type: string
        description: CMake build type
        default: Release
    executor: <<parameters.executor>>
    environment:
      IMAGESET: <<parameters.imageset>>
      CMAKE_VERSION: <<parameters.cmake>>
      CUDA_VERSION: <<parameters.cuda>>
      GCC_VERSION: <<parameters.gcc>>
      GDAL_VERSION: <<parameters.gdal>>
      EIGEN_VERSION: <<parameters.eigen>>
      PYBIND11_VERSION: <<parameters.pybind11>>
      PYTHON_VERSION: <<parameters.python>>
      BUILD_TYPE: <<parameters.build_type>>
    steps:
      - checkout
      - run:
          name: Build runtime environment
          working_directory: ci
          command: docker-compose build runtime
      - run:
          name: Build devel environment
          working_directory: ci
          command: docker-compose build devel
      - run:
          name: Configure
          working_directory: ci
          command: docker-compose build configure
      - run:
          name: Build
          working_directory: ci
          command: docker-compose build build
      - run:
          name: Install
          working_directory: ci
          command: docker-compose build install
      - run:
          name: Test
          working_directory: ci
          command: docker-compose run test

workflows:
  pr-checks:
    jobs:
      - linux-gpu-build-and-test:
          name: centos7-gpu_<<matrix.build_type>>
          matrix:
            parameters:
              build_type: ["Release", "Debug"]

      - linux-gpu-build-and-test:
          name: centos7-gpu_cmake-v3.18
          cmake: "3.18"

      - linux-gpu-build-and-test:
          name: centos7-gpu_gcc-v<<matrix.gcc>>_cuda-v<<matrix.cuda>>
          matrix:
            parameters:
              cuda: ["11-0", "11-1", "11-2", "11-3", "11-4"]
              gcc: ["9", "10", "11"]
            exclude:
              # Some CUDA + GNU compiler version combinations are excluded due
              # to restrictions on the CUDA host compiler. Prior to CUDA v11.4,
              # gcc>=11 is unsupported.
              - cuda: "11-0"
                gcc: "11"
              - cuda: "11-1"
                gcc: "11"
              - cuda: "11-2"
                gcc: "11"
              - cuda: "11-3"
                gcc: "11"

      - linux-gpu-build-and-test:
          name: centos7-gpu_gdal-v<<matrix.gdal>>
          matrix:
            parameters:
              gdal: ["2.4", "3.0", "3.4"]

      - linux-gpu-build-and-test:
          name: centos7-gpu_eigen-v3.3
          eigen: "3.3"

      - linux-gpu-build-and-test:
          name: centos7-gpu_pybind11-v2.5_python-v3.7
          pybind11: "2.5"
          python: "3.7"

      - linux-gpu-build-and-test:
          name: centos7-gpu_python-v<<matrix.python>>
          matrix:
            parameters:
              python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

      - linux-gpu-build-and-test:
          name: ubuntu2004-gpu
          imageset: ubuntu2004-gpu
