version: 2.1

executors:
  linux-cuda11-medium:
    resource_class: gpu.nvidia.medium
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01

jobs:
  linux-gpu-build-and-test:
    parameters:
      executor:
        type: string
        description: Host executor (must be a valid Linux GPU runner)
        default: linux-cuda11-medium
      imageset:
        type: string
        description: Docker image family {"centos7-gpu", "ubuntu2004-gpu"}
        default: centos7-gpu
      cmake:
        type: string
        description: CMake version string
        default: "3.21"
      cuda:
        type: string
        description: CUDA version string
        default: 11-4
      gcc:
        type: string
        description: GCC version string
        default: "11.2"
      gdal:
        type: string
        description: GDAL version string
        default: "3.4"
      eigen:
        type: string
        description: Eigen version string
        default: "3.4"
      pybind11:
        type: string
        description: pybind11 version string
        default: "2.8"
      python:
        type: string
        description: Python version string
        default: "3.10"
      build_type:
        type: string
        description: CMake build type
        default: Release
    executor: <<parameters.executor>>
    environment:
      IMAGESET: <<parameters.imageset>>
      CMAKE_VERSION: <<parameters.cmake>>
      CUDA_VERSION: <<parameters.cuda>>
      GCC_VERSION: <<parameters.gcc>>
      GDAL_VERSION: <<parameters.gdal>>
      EIGEN_VERSION: <<parameters.eigen>>
      PYBIND11_VERSION: <<parameters.pybind11>>
      PYTHON_VERSION: <<parameters.python>>
      BUILD_TYPE: <<parameters.build_type>>
    steps:
      - checkout
      - run:
          name: Build runtime environment
          working_directory: ci
          command: docker-compose build runtime
      - run:
          name: Build devel environment
          working_directory: ci
          command: docker-compose build devel
      - run:
          name: Configure
          working_directory: ci
          command: docker-compose build configure
      - run:
          name: Build
          working_directory: ci
          command: docker-compose build build
      - run:
          name: Install
          working_directory: ci
          command: docker-compose build install
      - run:
          name: Test
          working_directory: ci
          command: docker-compose run test

workflows:
  pr-checks:
    jobs:
      - linux-gpu-build-and-test:
          matrix:
            parameters:
              cmake: ["3.18", "3.21"]

      - linux-gpu-build-and-test:
          matrix:
            parameters:
              cuda: ["11-1", "11-4"]
              gcc: ["9", "10", "11"]

      - linux-gpu-build-and-test:
          matrix:
            parameters:
              gdal: ["2.4", "3.4"]

      - linux-gpu-build-and-test:
          matrix:
            parameters:
              eigen: ["3.3", "3.4"]

      - linux-gpu-build-and-test:
          matrix:
            parameters:
              pybind11: ["2.5", "2.8"]

      - linux-gpu-build-and-test:
          matrix:
            parameters:
              python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

      - linux-gpu-build-and-test:
          matrix:
            parameters:
              build_type: ["Release", "Debug"]
