#!groovy

pipeline {
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }
  agent { label 'opera-adt-build-fleet-gpu' }
  stages {
    stage("Check CUDA devices") {
      steps {
        sh "nvidia-smi -a"
      }
    }
    stage("Find Python interpreter") {
      steps {
        which python
      }
    }
  }
  post {
    success {
      echo 'I succeeded!'
    }
    unstable {
      echo 'I am unstable :/'
    }
    failure {
      echo 'I failed :('
    }
    changed {
      echo 'Things were different before...'
    }
  }
}
